apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secureship
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # After monitoring PVCs are bound
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: observeops
  source:
    repoURL: https://github.com/RohanReddy-M/observeops
    targetRevision: HEAD
    path: kubernetes/apps/secureship
  destination:
    server: https://kubernetes.default.svc
    namespace: observeops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
